[build]
publish = "."
functions = "netlify/
functions"
command = ""
  publish = "."
  
  [functions]
node_bundler = "esbuild"
external_node_modules = []

[[redirects]]
from = "/*"
to = "/remove-pro.html"
status = 200
